### ISSUE TITLE
Onclick callback

### ISSUE THREAD

**Issue by rafaellop** [jcesarmobile/plusOneButtonPlugin#9]
Would be great to have a way to add a callback for clicking the PlusOne button or some other way to know that user had some interaction with it.

**Comment by rodrigograca31** [comment]
Yheaa, this would be a nice feature.... Let me check if there's some event on the native side....

I have the code to center it... I need to contribute that code and maybe I could do this after it...

One of this days..... :)

**Comment by rafaellop** [comment]
Positioning is easy. For example:

``` javascript
var physicalScreenWidth = window.screen.width * window.devicePixelRatio;
var physicalScreenHeight = window.screen.height * window.devicePixelRatio;

var ypos = angular.element(document.querySelector('.indexplusyposbtn')).prop('offsetTop');

var params = {};
params.url = $rootScope.url_mygi;
params.size = 2; // tall (bubble) , size = 50px
params.annotation = 1;
params.position = { x : physicalScreenWidth - ((50 + 16) *  window.devicePixelRatio),
                                y : ((ypos + 16) * window.devicePixelRatio) };
plusOneButton.show(params);
```

In HTML you need to declare a container:
`<div class="indexplusyposbtn"></div>`

The `params.position` line is about position declaration. It's my position which is right top of the div, but you can easily convert this to have it centered.

**Comment by rodrigograca31** [comment]
@rafaellop Hummm, I was about to say that we could not map it and then I saw your code....

I've tried it and it doesn't show where it should.... it's slightly above....
And why 50+16 and ypos + 16?

I was originally talking about issue #5 ....

**Comment by rafaellop** [comment]
These are my hardcoded values. Remove them. To center you should just set the `x` for `params.positions` to `physicalScreenWidth / 2 - (btnwidth * window.devicePixelRatio)` btnwidth is the width of your button size, for example size = 2 is tall and it has 50px.

**Comment by rodrigograca31** [comment]
Yhea, `x` is simple... I've used this in `y` and it was not where it should be: `y: (ypos * window.devicePixelRatio)` it's a bit higher...

**Comment by rodrigograca31** [comment]
I will try to implement the click event now... Wish me luck! :)

**Comment by rodrigograca31** [comment]
@rafaellop or @jcesarmobile can you guys [take a look at my code](https://github.com/rodrigograca31/plusOneButtonPlugin/commit/8430bd5e110dfa73354700f23dd2e94a5be9f9b5)? I was able to detect the click event, and call a javascript function. But it's not working as it should.... 

It doesn't detect the first click, `System.out.println("1 Click!");` 

My Javascript:

``` javascript
window.plusOneButton.show({
    url: 'https://google.com',
    size: 2,
    annotation: 1,
    position: {
        x: 100,
        y: 100
    }
});
window.plusOneButton.onClick(function () {
    console.log('clicked!');
});
```

Also, I've created `PObtn` because I didn't knew how to referent it here: `cordova.startActivityForResult(PObtn, intent, 0);`

For those wondering how to develop/edit this plugin: you just need to clone it to a folder and run:
`cordova plugin rm cordova-plugin-plusonebutton && cordova plugin add ~/git/plusOneButtonPlugin/ && cordova run`

This removes and reapplies the plugin from the path `~/git/plusOneButtonPlugin/` then runs your project...

**Comment by rodrigograca31** [comment]
(and `import java.lang.System;` is just for debugging, will be removed....)

**Comment by jcesarmobile** [comment]
@rodrigograca31 thanks for trying.

I've just updated the plugin to add the listener.

`document.addEventListener("plusOneButtonClicked", onOneButtonClicked, false);`

**Comment by rafaellop** [comment]
@rodrigograca31 Thanks for this. Pitty that Google didn't decide to give callback for real +1 instead just clicks, but this is still handful. Thanks for your efforts Rodrigo!

**Comment by jcesarmobile** [comment]
What do you mean by "real +1"?

**Comment by rafaellop** [comment]
As real +1 click I mean a situation when a user gives +1 and not just clicks the PlusBTN. Giving +1 is a process of clicking the PlusBTN, then logging or selecting the account and then confirmation. I mean that would be great to know if a user has really given +1 not only that they clicked the icon. Unfortunately it seems that there's no callback for that situation.

**Comment by jcesarmobile** [comment]
I think it's possible to get for the intent result, will take a look

**Comment by rodrigograca31** [comment]
Yheaa, probably there's something "returned" to know what was the result....

**Comment by jcesarmobile** [comment]
Bad news, you can listen for the intent result, but the result code is not reliable. 
If the button has not been clicked and you click ok or share it will return -1
If the button has not been clicked and you click undo it will return 0
If the button has been clicked (it's in +1 status) and you click ok or share it will return 0
If the button has not been clicked (it's in +1 status) and you click undo it will return -1

I don´t think there is a way to know the status of the button, so that codes are useless

I can make the plugin return that codes, at least the first time you get the -1 you can be sure that it was an ok or share click
